#!/usr/bin/env node
/* AEL Academy — Build Data Script */

const fs = require('fs');
const path = require('path');

console.log('Building data.js...\n');

const academyPath = path.join(__dirname, '..', 'academy.json');
const questionsPath = path.join(__dirname, '..', 'questions.json');
const outputPath = path.join(__dirname, '..', 'data.js');

const academy = JSON.parse(fs.readFileSync(academyPath, 'utf8'));
const questions = JSON.parse(fs.readFileSync(questionsPath, 'utf8'));

const lines = [
  '// AEL Engineering Academy v1.0 — Embedded Data',
  '// Auto-generated by scripts/build-data.js — do not edit manually',
  '',
  `window.ACADEMY_DATA = ${JSON.stringify(academy, null, 0)};`,
  '',
  `window.QUESTIONS_DATA = ${JSON.stringify(questions, null, 0)};`,
  ''
];

fs.writeFileSync(outputPath, lines.join('\n'), 'utf8');

const size = (fs.statSync(outputPath).size / 1024 / 1024).toFixed(1);
console.log(`  data.js: ${size}MB`);
console.log(`  Academy: ${academy.weeks.length} weeks, ${academy.modules.length} modules`);
console.log(`  Questions: ${questions.questions.length} total`);
console.log('\nBuild complete.');
